file_format: "1"
id: pandawingsv1
name: PandaWings v1
type: shield
url: https://github.com/IndiePandaaaaa/PandaWings-kbd
requires: [seeeduino_xiao_ble]
features:
  - keys
  - leds
  - display
siblings:
  - pandawingsv1_left
  - pandawingsv1_right
