# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# INFO: the dongle is now working so there is only the dongle version available
---
include:
  - board: xiao_ble
    shield: settings_reset
  - board: xiao_ble
    shield: pandawings-i_dongle
  - board: xiao_ble
    shield: pandawings-i_left
  - board: xiao_ble
    shield: pandawings-i_right
